name: Auto Build

on:
  workflow_dispatch:
    # inputs:
    #   tags:
    #     description: 'Docker Tag'
    #     required: false
    #     default: 'latest'
  push:
    branches: [main,master]
    # Only build when files in these directories have been changed
    paths:
      - containers/**
      - template/**
  schedule:
    - cron:  '0 9 * * *' # UTC

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    - name: Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Update Images
      run: ./bin/01-update-images ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Images
      run: ./bin/03-build-images push

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: wernercd/terraria
        short-description: "Docker images to run a Terraria Server. Images with TShock Server are available."
